### ISSUE TITLE
Sourcing `setup.ps1` multiple times generates spurrious error: fixed in PR 27

### ISSUE THREAD

**Issue by KazNX** [colcon/colcon-powershell#31]
Hi,

I've noted that sourcing `setup.ps1` (Windows powershell) generates a spurrious error. This error has been fixed in [PR 27](https://github.com/colcon/colcon-powershell/pull/27), but has yet to be release. Can someone please update on when this might be release?

Thanks.

**Comment by jacobperron** [comment]
@dirk-thomas Can you make a new release? I've never done a release of a colcon package (or to PyPI) before.

Since https://github.com/colcon/colcon-powershell/pull/30 seems to depend on a change upstream, I guess we depend on a colcon-core release first.

**Comment by dirk-thomas** [comment]
I will try to take a look early next week.

**Comment by dirk-thomas** [comment]
I did a quick pass on tickets across various repositories. But unfortunately the state everything is in was less than optimal - e.g. many failing CI. For today I ran out of time. I will revisit this when I get another chance.

**Comment by Ace314159** [comment]
@dirk-thomas Can you please make a new release? It is really annoying to have these spurious errors when using Powershell.

**Comment by dirk-thomas** [comment]
@Ace314159 I am currently not using this tool and don't have any spare time to maintain it. Another maintainer will have to take care of this - likely after #32 which aims to fix the CI.

**Comment by cottsay** [comment]
0.3.7 has been released.
